In [1]:
import numpy as np

#Grupo 2

matriz_A = np.random.rand(20, 5)
print('Matriz A: ')
print(matriz_A)

matriz_B = np.random.normal(0, 10, size = (5, 7))
print('Matriz B: ')
print(matriz_B)

produto_matriz = matriz_A @ matriz_B
print('Poduto das matrizes: ')
print(produto_matriz)

print('3ª linha x 4ª coluna: ')
linha_x_coluna = np.dot(matriz_A[3:, ], matriz_B[:, 4])
print(linha_x_coluna)


matriz_final = np.dot(matriz_A, matriz_B[:, 4])
print('Matriz final: ')
print(matriz_final)

Matriz A: 
[[0.16999159 0.3439472  0.19738526 0.77852661 0.25992691]
 [0.67859535 0.00539164 0.20686218 0.87688435 0.84237611]
 [0.28767703 0.86388502 0.31659766 0.2676961  0.39216262]
 [0.42038331 0.85989432 0.18568216 0.44025188 0.71314206]
 [0.41488767 0.15406304 0.40144637 0.19803822 0.38052698]
 [0.46994044 0.77821541 0.08621136 0.40095995 0.13116263]
 [0.19158815 0.19112315 0.96678769 0.38558146 0.20741348]
 [0.54544956 0.26223112 0.33049183 0.78054583 0.44706934]
 [0.33398494 0.93842277 0.64085023 0.88659478 0.28775345]
 [0.09308415 0.26573672 0.59781729 0.11756559 0.42392913]
 [0.40257883 0.20939057 0.90547454 0.45265982 0.29256886]
 [0.65700826 0.05690104 0.83113338 0.45588448 0.57783641]
 [0.60566392 0.24694576 0.90213389 0.76755887 0.77354632]
 [0.90350028 0.39197806 0.61564932 0.45470425 0.46719256]
 [0.79790315 0.96708096 0.13701201 0.3866254  0.56899375]
 [0.60315915 0.60481293 0.41658955 0.08081154 0.86173232]
 [0.94944705 0.48188726 0.11900882 0.7417808  0.16260211]
 [0